### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BookWyrm114** [TheCSDev/mc-chunk-copy#4]
**Describe the feature you'd like**
A larger download size, perhaps a way to start a download, then move around in the world and the mod will automatically download all loaded chunks during the process. the download will stop when the user turns it off, or when they leave the server.

**Comment by TheCSDev** [comment]
Hello. Thank you for the feature request. I did plan on implementing this feature eventually, but I got too busy with many other things as well. Either way, I just finished implementing it, and if everything works as expected, I will soon publish it.
