### ISSUE TITLE
Increase max chunk saving limit to server render distance or player render distance; whichever is lowest

### ISSUE THREAD

**Issue by kaxon-dev** [TheCSDev/mc-chunk-copy#6]
**Describe the feature you'd like**
Currently the max chunk copy size is set to 8, but it often doesn't capture enough. For example, I use the bobby mod: https://github.com/Johni0702/bobby. This mod allows me to set my render distance on my client as high as I like and then walk around the server to eventually load in the chunks that were previously unviewable.

If this feature is too difficult, could perhaps there be a /chunkcopy copy name **all** addition which saves all presently rendered chunks on the client? Thanks.

**Comment by kaxon-dev** [comment]
(closed because autoCopy is good enough for me)

**Comment by TheCSDev** [comment]
Having this be resolved would be great, however as mentioned in issue #5, the reason I limited the radius (not diameter) to 8 is because of performance. It simply costs too much performace to have it go anywhere above 8 (aka 16x16 chunks).
